# Generated by Django 3.1.3 on 2020-11-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cart_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(default='pics/amazfit1.jpg', max_length=50),
            preserve_default=False,
        ),
    ]
